import type { AirportInfo } from "./quality-of-life.types.js";

export const FAA_AIRPORT_REFERENCE_AS_OF = "2025-01-01";
export const FAA_AIRPORT_SOURCE_URL = "https://www.faa.gov/air_traffic/flight_info/aeronav/aero_data/Airport_Data/";

export const STATE_PRIMARY_AIRPORTS: Record<string, AirportInfo> = {
  AL: { code: "BHM", name: "Birmingham-Shuttlesworth International Airport", city: "Birmingham", state: "AL", category: "primary-commercial" },
  AK: { code: "ANC", name: "Ted Stevens Anchorage International Airport", city: "Anchorage", state: "AK", category: "primary-commercial" },
  AZ: { code: "PHX", name: "Phoenix Sky Harbor International Airport", city: "Phoenix", state: "AZ", category: "primary-commercial" },
  AR: { code: "XNA", name: "Northwest Arkansas National Airport", city: "Bentonville", state: "AR", category: "primary-commercial" },
  CA: { code: "LAX", name: "Los Angeles International Airport", city: "Los Angeles", state: "CA", category: "primary-commercial" },
  CO: { code: "DEN", name: "Denver International Airport", city: "Denver", state: "CO", category: "primary-commercial" },
  CT: { code: "BDL", name: "Bradley International Airport", city: "Windsor Locks", state: "CT", category: "primary-commercial" },
  DE: { code: "PHL", name: "Philadelphia International Airport", city: "Philadelphia", state: "PA", category: "primary-commercial" },
  DC: { code: "DCA", name: "Ronald Reagan Washington National Airport", city: "Washington", state: "DC", category: "primary-commercial" },
  FL: { code: "MCO", name: "Orlando International Airport", city: "Orlando", state: "FL", category: "primary-commercial" },
  GA: { code: "ATL", name: "Hartsfield-Jackson Atlanta International Airport", city: "Atlanta", state: "GA", category: "primary-commercial" },
  HI: { code: "HNL", name: "Daniel K. Inouye International Airport", city: "Honolulu", state: "HI", category: "primary-commercial" },
  ID: { code: "BOI", name: "Boise Airport", city: "Boise", state: "ID", category: "primary-commercial" },
  IL: { code: "ORD", name: "Chicago O'Hare International Airport", city: "Chicago", state: "IL", category: "primary-commercial" },
  IN: { code: "IND", name: "Indianapolis International Airport", city: "Indianapolis", state: "IN", category: "primary-commercial" },
  IA: { code: "DSM", name: "Des Moines International Airport", city: "Des Moines", state: "IA", category: "primary-commercial" },
  KS: { code: "ICT", name: "Wichita Dwight D. Eisenhower National Airport", city: "Wichita", state: "KS", category: "primary-commercial" },
  KY: { code: "SDF", name: "Louisville Muhammad Ali International Airport", city: "Louisville", state: "KY", category: "primary-commercial" },
  LA: { code: "MSY", name: "Louis Armstrong New Orleans International Airport", city: "New Orleans", state: "LA", category: "primary-commercial" },
  ME: { code: "PWM", name: "Portland International Jetport", city: "Portland", state: "ME", category: "primary-commercial" },
  MD: { code: "BWI", name: "Baltimore/Washington International Thurgood Marshall Airport", city: "Baltimore", state: "MD", category: "primary-commercial" },
  MA: { code: "BOS", name: "Boston Logan International Airport", city: "Boston", state: "MA", category: "primary-commercial" },
  MI: { code: "DTW", name: "Detroit Metropolitan Wayne County Airport", city: "Detroit", state: "MI", category: "primary-commercial" },
  MN: { code: "MSP", name: "Minneapolis-Saint Paul International Airport", city: "Minneapolis", state: "MN", category: "primary-commercial" },
  MS: { code: "JAN", name: "Jackson-Medgar Wiley Evers International Airport", city: "Jackson", state: "MS", category: "primary-commercial" },
  MO: { code: "MCI", name: "Kansas City International Airport", city: "Kansas City", state: "MO", category: "primary-commercial" },
  MT: { code: "BZN", name: "Bozeman Yellowstone International Airport", city: "Belgrade", state: "MT", category: "primary-commercial" },
  NE: { code: "OMA", name: "Eppley Airfield", city: "Omaha", state: "NE", category: "primary-commercial" },
  NV: { code: "LAS", name: "Harry Reid International Airport", city: "Las Vegas", state: "NV", category: "primary-commercial" },
  NH: { code: "MHT", name: "Manchester-Boston Regional Airport", city: "Manchester", state: "NH", category: "primary-commercial" },
  NJ: { code: "EWR", name: "Newark Liberty International Airport", city: "Newark", state: "NJ", category: "primary-commercial" },
  NM: { code: "ABQ", name: "Albuquerque International Sunport", city: "Albuquerque", state: "NM", category: "primary-commercial" },
  NY: { code: "JFK", name: "John F. Kennedy International Airport", city: "New York", state: "NY", category: "primary-commercial" },
  NC: { code: "CLT", name: "Charlotte Douglas International Airport", city: "Charlotte", state: "NC", category: "primary-commercial" },
  ND: { code: "FAR", name: "Hector International Airport", city: "Fargo", state: "ND", category: "primary-commercial" },
  OH: { code: "CMH", name: "John Glenn Columbus International Airport", city: "Columbus", state: "OH", category: "primary-commercial" },
  OK: { code: "OKC", name: "Will Rogers World Airport", city: "Oklahoma City", state: "OK", category: "primary-commercial" },
  OR: { code: "PDX", name: "Portland International Airport", city: "Portland", state: "OR", category: "primary-commercial" },
  PA: { code: "PHL", name: "Philadelphia International Airport", city: "Philadelphia", state: "PA", category: "primary-commercial" },
  RI: { code: "PVD", name: "Rhode Island T. F. Green International Airport", city: "Warwick", state: "RI", category: "primary-commercial" },
  SC: { code: "CHS", name: "Charleston International Airport", city: "North Charleston", state: "SC", category: "primary-commercial" },
  SD: { code: "FSD", name: "Sioux Falls Regional Airport", city: "Sioux Falls", state: "SD", category: "primary-commercial" },
  TN: { code: "BNA", name: "Nashville International Airport", city: "Nashville", state: "TN", category: "primary-commercial" },
  TX: { code: "DFW", name: "Dallas Fort Worth International Airport", city: "Dallas", state: "TX", category: "primary-commercial" },
  UT: { code: "SLC", name: "Salt Lake City International Airport", city: "Salt Lake City", state: "UT", category: "primary-commercial" },
  VT: { code: "BTV", name: "Patrick Leahy Burlington International Airport", city: "South Burlington", state: "VT", category: "primary-commercial" },
  VA: { code: "DCA", name: "Ronald Reagan Washington National Airport", city: "Washington", state: "DC", category: "primary-commercial" },
  WA: { code: "SEA", name: "Seattle-Tacoma International Airport", city: "Seattle", state: "WA", category: "primary-commercial" },
  WV: { code: "CRW", name: "West Virginia International Yeager Airport", city: "Charleston", state: "WV", category: "primary-commercial" },
  WI: { code: "MKE", name: "Milwaukee Mitchell International Airport", city: "Milwaukee", state: "WI", category: "primary-commercial" },
  WY: { code: "JAC", name: "Jackson Hole Airport", city: "Jackson", state: "WY", category: "primary-commercial" },
};
