// Verified MSA (CBSA) codes for BLS OEWS API v2 queries.
//
// Verification method: for each candidate 5-digit OMB CBSA code, constructed the OEWS
// series ID `OEUM` + 7-digit zero-padded area code + `000000` (all industries) +
// `000000` (all occupations) + `01` (employment datatype) and queried
// https://api.bls.gov/publicAPI/v2/timeseries/data/<seriesId>?catalog=true
// Each row below was accepted only after confirming `Results.series[0].catalog.area`
// in the live response names the expected metro (exact or a documented BLS naming
// variant of the same OMB CBSA, e.g. BLS still returns "Birmingham, AL" for CBSA 13820
// rather than the current OMB name "Birmingham-Hoover, AL"). The `name` field below is
// the literal `catalog.area` string BLS returned, not a hand-typed OMB name.
//
// Excluded after verification (do not re-add without re-verifying against the live API):
//   - 17460 "Cleveland, OH" (Cleveland-Elyria, OH) — a real, current OMB CBSA code with
//     published OEWS flat-file reports, but the live v2 timeseries API returns
//     "Series does not exist" for every occupation/datatype combination tried
//     (all-occupations employment, all-occupations median wage, and Software Developers
//     employment were all tested). Root cause unconfirmed — may be a BLS API-side gap
//     distinct from the flat-file data. Needs re-investigation before Cleveland can be added.
//   - 27900 (guessed as "Jefferson City, MO") — live API resolves this code to
//     "Joplin, MO-KS" instead, i.e. the guess was wrong. Jefferson City's real CBSA code
//     was not identified; do not fabricate one.
//
// Format: cbsaCode is the raw 5-digit CBSA code (caller zero-pads to 7 for the series ID).
export const MSA_CODES: Array<{ cbsaCode: string; name: string; cities: string[]; states: string[] }> = [
  { cbsaCode: '35620', name: 'New York-Newark-Jersey City, NY-NJ', cities: ['New York', 'Newark', 'Jersey City'], states: ['NY', 'NJ'] },
  { cbsaCode: '31080', name: 'Los Angeles-Long Beach-Anaheim, CA', cities: ['Los Angeles', 'Long Beach', 'Anaheim'], states: ['CA'] },
  { cbsaCode: '16980', name: 'Chicago-Naperville-Elgin, IL-IN', cities: ['Chicago', 'Naperville', 'Elgin'], states: ['IL', 'IN'] },
  { cbsaCode: '19100', name: 'Dallas-Fort Worth-Arlington, TX', cities: ['Dallas', 'Fort Worth', 'Arlington'], states: ['TX'] },
  { cbsaCode: '26420', name: 'Houston-Pasadena-The Woodlands, TX', cities: ['Houston', 'Pasadena', 'The Woodlands'], states: ['TX'] },
  { cbsaCode: '47900', name: 'Washington-Arlington-Alexandria, DC-VA-MD-WV', cities: ['Washington', 'Arlington', 'Alexandria'], states: ['DC', 'VA', 'MD', 'WV'] },
  { cbsaCode: '33100', name: 'Miami-Fort Lauderdale-West Palm Beach, FL', cities: ['Miami', 'Fort Lauderdale', 'West Palm Beach'], states: ['FL'] },
  { cbsaCode: '37980', name: 'Philadelphia-Camden-Wilmington, PA-NJ-DE-MD', cities: ['Philadelphia', 'Camden', 'Wilmington'], states: ['PA', 'NJ', 'DE', 'MD'] },
  { cbsaCode: '12060', name: 'Atlanta-Sandy Springs-Roswell, GA', cities: ['Atlanta', 'Sandy Springs', 'Roswell'], states: ['GA'] },
  { cbsaCode: '38060', name: 'Phoenix-Mesa-Chandler, AZ', cities: ['Phoenix', 'Mesa', 'Chandler'], states: ['AZ'] },
  { cbsaCode: '14460', name: 'Boston-Cambridge-Newton, MA-NH', cities: ['Boston', 'Cambridge', 'Newton'], states: ['MA', 'NH'] },
  { cbsaCode: '41860', name: 'San Francisco-Oakland-Fremont, CA', cities: ['San Francisco', 'Oakland', 'Fremont'], states: ['CA'] },
  { cbsaCode: '40140', name: 'Riverside-San Bernardino-Ontario, CA', cities: ['Riverside', 'San Bernardino', 'Ontario'], states: ['CA'] },
  { cbsaCode: '19820', name: 'Detroit-Warren-Dearborn, MI', cities: ['Detroit', 'Warren', 'Dearborn'], states: ['MI'] },
  { cbsaCode: '42660', name: 'Seattle-Tacoma-Bellevue, WA', cities: ['Seattle', 'Tacoma', 'Bellevue'], states: ['WA'] },
  { cbsaCode: '33460', name: 'Minneapolis-St. Paul-Bloomington, MN-WI', cities: ['Minneapolis', 'St. Paul', 'Bloomington'], states: ['MN', 'WI'] },
  { cbsaCode: '41740', name: 'San Diego-Chula Vista-Carlsbad, CA', cities: ['San Diego', 'Chula Vista', 'Carlsbad'], states: ['CA'] },
  { cbsaCode: '45300', name: 'Tampa-St. Petersburg-Clearwater, FL', cities: ['Tampa', 'St. Petersburg', 'Clearwater'], states: ['FL'] },
  { cbsaCode: '19740', name: 'Denver-Aurora-Centennial, CO', cities: ['Denver', 'Aurora', 'Centennial'], states: ['CO'] },
  { cbsaCode: '12580', name: 'Baltimore-Columbia-Towson, MD', cities: ['Baltimore', 'Columbia', 'Towson'], states: ['MD'] },
  { cbsaCode: '41180', name: 'St. Louis, MO-IL', cities: ['St. Louis'], states: ['MO', 'IL'] },
  { cbsaCode: '36740', name: 'Orlando-Kissimmee-Sanford, FL', cities: ['Orlando', 'Kissimmee', 'Sanford'], states: ['FL'] },
  { cbsaCode: '16740', name: 'Charlotte-Concord-Gastonia, NC-SC', cities: ['Charlotte', 'Concord', 'Gastonia'], states: ['NC', 'SC'] },
  { cbsaCode: '41700', name: 'San Antonio-New Braunfels, TX', cities: ['San Antonio', 'New Braunfels'], states: ['TX'] },
  { cbsaCode: '38900', name: 'Portland-Vancouver-Hillsboro, OR-WA', cities: ['Portland', 'Vancouver', 'Hillsboro'], states: ['OR', 'WA'] },
  { cbsaCode: '40900', name: 'Sacramento-Roseville-Folsom, CA', cities: ['Sacramento', 'Roseville', 'Folsom'], states: ['CA'] },
  { cbsaCode: '38300', name: 'Pittsburgh, PA', cities: ['Pittsburgh'], states: ['PA'] },
  { cbsaCode: '12420', name: 'Austin-Round Rock-San Marcos, TX', cities: ['Austin', 'Round Rock', 'San Marcos'], states: ['TX'] },
  { cbsaCode: '29820', name: 'Las Vegas-Henderson-North Las Vegas, NV', cities: ['Las Vegas', 'Henderson', 'North Las Vegas'], states: ['NV'] },
  { cbsaCode: '17140', name: 'Cincinnati, OH-KY-IN', cities: ['Cincinnati'], states: ['OH', 'KY', 'IN'] },
  { cbsaCode: '28140', name: 'Kansas City, MO-KS', cities: ['Kansas City'], states: ['MO', 'KS'] },
  { cbsaCode: '18140', name: 'Columbus, OH', cities: ['Columbus'], states: ['OH'] },
  { cbsaCode: '26900', name: 'Indianapolis-Carmel-Greenwood, IN', cities: ['Indianapolis', 'Carmel', 'Greenwood'], states: ['IN'] },
  { cbsaCode: '41940', name: 'San Jose-Sunnyvale-Santa Clara, CA', cities: ['San Jose', 'Sunnyvale', 'Santa Clara'], states: ['CA'] },
  { cbsaCode: '34980', name: 'Nashville-Davidson--Murfreesboro--Franklin, TN', cities: ['Nashville', 'Davidson', 'Murfreesboro', 'Franklin'], states: ['TN'] },
  { cbsaCode: '47260', name: 'Virginia Beach-Chesapeake-Norfolk, VA-NC', cities: ['Virginia Beach', 'Chesapeake', 'Norfolk'], states: ['VA', 'NC'] },
  { cbsaCode: '39300', name: 'Providence-Warwick, RI-MA', cities: ['Providence', 'Warwick'], states: ['RI', 'MA'] },
  { cbsaCode: '33340', name: 'Milwaukee-Waukesha, WI', cities: ['Milwaukee', 'Waukesha'], states: ['WI'] },
  { cbsaCode: '27260', name: 'Jacksonville, FL', cities: ['Jacksonville'], states: ['FL'] },
  { cbsaCode: '36420', name: 'Oklahoma City, OK', cities: ['Oklahoma City'], states: ['OK'] },
  { cbsaCode: '39580', name: 'Raleigh-Cary, NC', cities: ['Raleigh', 'Cary'], states: ['NC'] },
  { cbsaCode: '32820', name: 'Memphis, TN-MS-AR', cities: ['Memphis'], states: ['TN', 'MS', 'AR'] },
  { cbsaCode: '40060', name: 'Richmond, VA', cities: ['Richmond'], states: ['VA'] },
  { cbsaCode: '31140', name: 'Louisville/Jefferson County, KY-IN', cities: ['Louisville', 'Jefferson County'], states: ['KY', 'IN'] },
  { cbsaCode: '35380', name: 'New Orleans-Metairie, LA', cities: ['New Orleans', 'Metairie'], states: ['LA'] },
  { cbsaCode: '41620', name: 'Salt Lake City-Murray, UT', cities: ['Salt Lake City', 'Murray'], states: ['UT'] },
  { cbsaCode: '25540', name: 'Hartford-West Hartford-East Hartford, CT', cities: ['Hartford', 'West Hartford', 'East Hartford'], states: ['CT'] },
  { cbsaCode: '15380', name: 'Buffalo-Cheektowaga, NY', cities: ['Buffalo', 'Cheektowaga'], states: ['NY'] },
  { cbsaCode: '13820', name: 'Birmingham, AL', cities: ['Birmingham'], states: ['AL'] },
  { cbsaCode: '40380', name: 'Rochester, NY', cities: ['Rochester'], states: ['NY'] },
  { cbsaCode: '24340', name: 'Grand Rapids-Wyoming-Kentwood, MI', cities: ['Grand Rapids', 'Wyoming', 'Kentwood'], states: ['MI'] },
  { cbsaCode: '46060', name: 'Tucson, AZ', cities: ['Tucson'], states: ['AZ'] },
  { cbsaCode: '46520', name: 'Urban Honolulu, HI', cities: ['Urban Honolulu'], states: ['HI'] },
  { cbsaCode: '46140', name: 'Tulsa, OK', cities: ['Tulsa'], states: ['OK'] },
  { cbsaCode: '23420', name: 'Fresno, CA', cities: ['Fresno'], states: ['CA'] },
  { cbsaCode: '49340', name: 'Worcester, MA', cities: ['Worcester'], states: ['MA'] },
  { cbsaCode: '36540', name: 'Omaha, NE-IA', cities: ['Omaha'], states: ['NE', 'IA'] },
  { cbsaCode: '14860', name: 'Bridgeport-Stamford-Danbury, CT', cities: ['Bridgeport', 'Stamford', 'Danbury'], states: ['CT'] },
  { cbsaCode: '24860', name: 'Greenville-Anderson-Greer, SC', cities: ['Greenville', 'Anderson', 'Greer'], states: ['SC'] },
  { cbsaCode: '10740', name: 'Albuquerque, NM', cities: ['Albuquerque'], states: ['NM'] },
  { cbsaCode: '12540', name: 'Bakersfield-Delano, CA', cities: ['Bakersfield', 'Delano'], states: ['CA'] },
  { cbsaCode: '10580', name: 'Albany-Schenectady-Troy, NY', cities: ['Albany', 'Schenectady', 'Troy'], states: ['NY'] },
  { cbsaCode: '35300', name: 'New Haven, CT', cities: ['New Haven'], states: ['CT'] },
  { cbsaCode: '12940', name: 'Baton Rouge, LA', cities: ['Baton Rouge'], states: ['LA'] },
  { cbsaCode: '32580', name: 'McAllen-Edinburg-Mission, TX', cities: ['McAllen', 'Edinburg', 'Mission'], states: ['TX'] },
  { cbsaCode: '17900', name: 'Columbia, SC', cities: ['Columbia'], states: ['SC'] },
  { cbsaCode: '16700', name: 'Charleston-North Charleston, SC', cities: ['Charleston', 'North Charleston'], states: ['SC'] },
  { cbsaCode: '19430', name: 'Dayton-Kettering-Beavercreek, OH', cities: ['Dayton', 'Kettering', 'Beavercreek'], states: ['OH'] },
  { cbsaCode: '28940', name: 'Knoxville, TN', cities: ['Knoxville'], states: ['TN'] },
  { cbsaCode: '21340', name: 'El Paso, TX', cities: ['El Paso'], states: ['TX'] },
  { cbsaCode: '10900', name: 'Allentown-Bethlehem-Easton, PA-NJ', cities: ['Allentown', 'Bethlehem', 'Easton'], states: ['PA', 'NJ'] },
  { cbsaCode: '35840', name: 'North Port-Bradenton-Sarasota, FL', cities: ['North Port', 'Bradenton', 'Sarasota'], states: ['FL'] },
  { cbsaCode: '24660', name: 'Greensboro-High Point, NC', cities: ['Greensboro', 'High Point'], states: ['NC'] },
  { cbsaCode: '37100', name: 'Oxnard-Thousand Oaks-Ventura, CA', cities: ['Oxnard', 'Thousand Oaks', 'Ventura'], states: ['CA'] },
  { cbsaCode: '10420', name: 'Akron, OH', cities: ['Akron'], states: ['OH'] },
  { cbsaCode: '15980', name: 'Cape Coral-Fort Myers, FL', cities: ['Cape Coral', 'Fort Myers'], states: ['FL'] },
  { cbsaCode: '17820', name: 'Colorado Springs, CO', cities: ['Colorado Springs'], states: ['CO'] },
  { cbsaCode: '14260', name: 'Boise City, ID', cities: ['Boise City'], states: ['ID'] },
  { cbsaCode: '44700', name: 'Stockton-Lodi, CA', cities: ['Stockton', 'Lodi'], states: ['CA'] },
  { cbsaCode: '48620', name: 'Wichita, KS', cities: ['Wichita'], states: ['KS'] },
  { cbsaCode: '49180', name: 'Winston-Salem, NC', cities: ['Winston', 'Salem'], states: ['NC'] },
  { cbsaCode: '45780', name: 'Toledo, OH', cities: ['Toledo'], states: ['OH'] },
  { cbsaCode: '31540', name: 'Madison, WI', cities: ['Madison'], states: ['WI'] },
  { cbsaCode: '19780', name: 'Des Moines-West Des Moines, IA', cities: ['Des Moines', 'West Des Moines'], states: ['IA'] },
  { cbsaCode: '30780', name: 'Little Rock-North Little Rock-Conway, AR', cities: ['Little Rock', 'North Little Rock', 'Conway'], states: ['AR'] },
  { cbsaCode: '19660', name: 'Deltona-Daytona Beach-Ormond Beach, FL', cities: ['Deltona', 'Daytona Beach', 'Ormond Beach'], states: ['FL'] },
  { cbsaCode: '45060', name: 'Syracuse, NY', cities: ['Syracuse'], states: ['NY'] },
  { cbsaCode: '20500', name: 'Durham-Chapel Hill, NC', cities: ['Durham', 'Chapel Hill'], states: ['NC'] },
  { cbsaCode: '29460', name: 'Lakeland-Winter Haven, FL', cities: ['Lakeland', 'Winter Haven'], states: ['FL'] },
  { cbsaCode: '39340', name: 'Provo-Orem-Lehi, UT', cities: ['Provo', 'Orem', 'Lehi'], states: ['UT'] },
  { cbsaCode: '38860', name: 'Portland-South Portland, ME', cities: ['Portland', 'South Portland'], states: ['ME'] },
  { cbsaCode: '16860', name: 'Chattanooga, TN-GA', cities: ['Chattanooga'], states: ['TN', 'GA'] },
  { cbsaCode: '37340', name: 'Palm Bay-Melbourne-Titusville, FL', cities: ['Palm Bay', 'Melbourne', 'Titusville'], states: ['FL'] },
  { cbsaCode: '44140', name: 'Springfield, MA', cities: ['Springfield'], states: ['MA'] },
  { cbsaCode: '49660', name: 'Youngstown-Warren, OH', cities: ['Youngstown', 'Warren'], states: ['OH'] },
  { cbsaCode: '22220', name: 'Fayetteville-Springdale-Rogers, AR', cities: ['Fayetteville', 'Springdale', 'Rogers'], states: ['AR'] },
  { cbsaCode: '36260', name: 'Ogden, UT', cities: ['Ogden'], states: ['UT'] },
  { cbsaCode: '29540', name: 'Lancaster, PA', cities: ['Lancaster'], states: ['PA'] },
  { cbsaCode: '30460', name: 'Lexington-Fayette, KY', cities: ['Lexington', 'Fayette'], states: ['KY'] },
  { cbsaCode: '11700', name: 'Asheville, NC', cities: ['Asheville'], states: ['NC'] },
  { cbsaCode: '25420', name: 'Harrisburg-Carlisle, PA', cities: ['Harrisburg', 'Carlisle'], states: ['PA'] },
  { cbsaCode: '12260', name: 'Augusta-Richmond County, GA-SC', cities: ['Augusta', 'Richmond County'], states: ['GA', 'SC'] },
  { cbsaCode: '44060', name: 'Spokane-Spokane Valley, WA', cities: ['Spokane', 'Spokane Valley'], states: ['WA'] },
  { cbsaCode: '18580', name: 'Corpus Christi, TX', cities: ['Corpus Christi'], states: ['TX'] },
  { cbsaCode: '28660', name: 'Killeen-Temple, TX', cities: ['Killeen', 'Temple'], states: ['TX'] },
  { cbsaCode: '23060', name: 'Fort Wayne, IN', cities: ['Fort Wayne'], states: ['IN'] },
  { cbsaCode: '11260', name: 'Anchorage, AK', cities: ['Anchorage'], states: ['AK'] },
  { cbsaCode: '39900', name: 'Reno, NV', cities: ['Reno'], states: ['NV'] },
  { cbsaCode: '17980', name: 'Columbus, GA-AL', cities: ['Columbus'], states: ['GA', 'AL'] },
  { cbsaCode: '34820', name: 'Myrtle Beach-Conway-North Myrtle Beach, SC', cities: ['Myrtle Beach', 'Conway', 'North Myrtle Beach'], states: ['SC'] },
  { cbsaCode: '29620', name: 'Lansing-East Lansing, MI', cities: ['Lansing', 'East Lansing'], states: ['MI'] },
  { cbsaCode: '42340', name: 'Savannah, GA', cities: ['Savannah'], states: ['GA'] },
  { cbsaCode: '26620', name: 'Huntsville, AL', cities: ['Huntsville'], states: ['AL'] },
  { cbsaCode: '33700', name: 'Modesto, CA', cities: ['Modesto'], states: ['CA'] },
  { cbsaCode: '47300', name: 'Visalia, CA', cities: ['Visalia'], states: ['CA'] },
  { cbsaCode: '37860', name: 'Pensacola-Ferry Pass-Brent, FL', cities: ['Pensacola', 'Ferry Pass', 'Brent'], states: ['FL'] },
  { cbsaCode: '41420', name: 'Salem, OR', cities: ['Salem'], states: ['OR'] },
  { cbsaCode: '37900', name: 'Peoria, IL', cities: ['Peoria'], states: ['IL'] },
  { cbsaCode: '40420', name: 'Rockford, IL', cities: ['Rockford'], states: ['IL'] },
  { cbsaCode: '45940', name: 'Trenton-Princeton, NJ', cities: ['Trenton', 'Princeton'], states: ['NJ'] },
  { cbsaCode: '43780', name: 'South Bend-Mishawaka, IN-MI', cities: ['South Bend', 'Mishawaka'], states: ['IN', 'MI'] },
  { cbsaCode: '31700', name: 'Manchester-Nashua, NH', cities: ['Manchester', 'Nashua'], states: ['NH'] },
  { cbsaCode: '20260', name: 'Duluth, MN-WI', cities: ['Duluth'], states: ['MN', 'WI'] },
  { cbsaCode: '22660', name: 'Fort Collins-Loveland, CO', cities: ['Fort Collins', 'Loveland'], states: ['CO'] },
  { cbsaCode: '34940', name: 'Naples-Marco Island, FL', cities: ['Naples', 'Marco Island'], states: ['FL'] },
  { cbsaCode: '24580', name: 'Green Bay, WI', cities: ['Green Bay'], states: ['WI'] },
  { cbsaCode: '28020', name: 'Kalamazoo-Portage, MI', cities: ['Kalamazoo', 'Portage'], states: ['MI'] },
  { cbsaCode: '45820', name: 'Topeka, KS', cities: ['Topeka'], states: ['KS'] },
  { cbsaCode: '21780', name: 'Evansville, IN', cities: ['Evansville'], states: ['IN'] },
  { cbsaCode: '16620', name: 'Charleston, WV', cities: ['Charleston'], states: ['WV'] },
  { cbsaCode: '48900', name: 'Wilmington, NC', cities: ['Wilmington'], states: ['NC'] },
  { cbsaCode: '15180', name: 'Brownsville-Harlingen, TX', cities: ['Brownsville', 'Harlingen'], states: ['TX'] },
  { cbsaCode: '45220', name: 'Tallahassee, FL', cities: ['Tallahassee'], states: ['FL'] },
  { cbsaCode: '27140', name: 'Jackson, MS', cities: ['Jackson'], states: ['MS'] },
  { cbsaCode: '33860', name: 'Montgomery, AL', cities: ['Montgomery'], states: ['AL'] },
  { cbsaCode: '44100', name: 'Springfield, IL', cities: ['Springfield'], states: ['IL'] },
  { cbsaCode: '42140', name: 'Santa Fe, NM', cities: ['Santa Fe'], states: ['NM'] },
  { cbsaCode: '36500', name: 'Olympia-Lacey-Tumwater, WA', cities: ['Olympia', 'Lacey', 'Tumwater'], states: ['WA'] },
];
